config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  resources :boards do
    resources :lists
  end

  resources :lists do
  resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :destroy, :update]
  
  def index
    @boards = Board.all
  end

  def show
    @lists = @board.lists
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:board_name)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  
  def index
    @lists = @board.lists
  end

  def show
    @tasks = @list.tasks
  end

  def new
    @list = @board.lists.new
  end

  def edit
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to board_path(@board,@list)
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to board_path(@board, @list)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end


  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:list_name, :board_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = @list.tasks
  end

  def show
  end

  def new
    @task = @list.tasks.new
  end

  def edit
    render :edit
  end

  def create
    @task = @list.tasks.new(task_params)

    if @task.save
      redirect_to list_task_path(@list,@task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to list_task_path(@list, @task)
    else
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    redirect_to list_tasks_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name, :priority, :description, :list_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%=  form_with(model: @board, local: true, class: "ui form") do |f|%>
    <div class="field">
    <%= f.label :board_name %>
    <%= f.text_field :board_name, required: true, placeholder: "Board Name" %>
    </div>
    <%= f.submit nil, class: "ui blue button" %>
    <% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<h1 class="ui header">Boards Home</h1>
<% @boards.each do |board| %>
<ul>
<li><h1><%=board.board_name%></h1>
</ul>
<%= link_to "Show", board_path(board), class: "ui blue button" %>
<%= link_to "Edit", edit_board_path(board), class: "ui green button" %>
<%= link_to "Delete", board_path(board), method: :delete, class: "ui red button" %>
<%end %>
<hr />
<br />
<%= link_to "New Board", new_board_path, class: "ui yellow button" %>

app/views/boards/new.html.erb
<h1>Add Board</h1>

<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<div class="ui card">
    <div class="content">
    <p class="header"><%= "Board:" %>
    <p class="header"><%= @board.board_name %>
    </p>
<%= "Lists:" %>
<% @lists.each do |list| %>
    <ul>
    <li><h1><%=list.list_name%></h1></li>
    </ul>
    
    <%= link_to "Show", board_list_path(@board, list), class: "ui blue button" %>
    <%= link_to "Edit", edit_board_list_path(@board, list), class: "ui green button" %>
    <%= link_to "Delete", board_list_path(@board, list), method: :delete, class: "ui red button" %>
    <% end %>

    <hr />
    <br />
 
 <%= link_to "Add List", new_board_list_path(@board), class: "ui yellow button" %>
 

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
<%= link_to "Boards", boards_path, class: "item" %>
<%= link_to "Add Board", new_board_path, class: "item" %>


</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%=  form_with(model: [@board, @list], local: true, class: "ui form") do |f|%>
    <div class="field">
    <%= f.label :list_name %>
    <%= f.text_field :list_name, required: true, placeholder: "List Name" %>
    </div>
    <%= f.submit nil, class: "ui blue button" %>
    <% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div class="ui card">
    <div class="content">
    <p class="header"><%= "Board:" %>
    <p class="header"><%= @board.board_name %>
    </p>
<%= "Lists:" %>
<% @lists.each do |list| %>
    <ul>
    <li><h1><%=list.list_name%></h1></li>
    </ul>
    
    <%= link_to "Show", board_list_path(@board, list), class: "ui blue button" %>
    <%= link_to "Edit", edit_board_list_path(@board, list), class: "ui green button" %>
    <%= link_to "Delete", board_list_path(@board, list), method: :delete, class: "ui red button" %>
    <% end %>

    <hr />
    <br />
 
 <%= link_to "Add List", new_board_list_path(@board), class: "ui yellow button" %>
 

app/views/lists/new.html.erb
 <h1>Add List</h1>
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<div class="ui card">
    <div class="content">
    <p class="header"><%= "List:" %>
    <p class="header"><%= @list.list_name %>
    </p>

<%= "Tasks:" %>
<% @tasks.each do |task| %>
    <ul>
    <li><h1><%=task.task_name%></h1></li>
    <li><%= "Priority: " %><%= task.priority %>
    </ul>  
    <%= link_to "Show", list_task_path(@list, task), class: "ui blue button" %>
    <% end %>

    <hr />
    <br />
 
 <%= link_to "Add Task", new_list_task_path(@list) , class: "ui yellow button" %>

app/views/tasks/_form.html.erb
<%=  form_with(model: [@list, @task], local: true, class: "ui form") do |f|%>
    <div class="field">
    <%= f.label :task_name %>
    <%= f.text_field :task_name, required: true, placeholder: "Task Name" %>
    </div>
    <div class="field">
    <%= f.label :task_description %>
    <%= f.text_field :task_description, required: true, placeholder: "Description" %>
    </div>
    <div class="field">
    <%= f.label :task_priority %>
    <%= f.text_field :task_priority, required: true, placeholder: "Priority" %>
    </div>
    <%= f.submit nil, class: "ui blue button" %>
    <% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="ui card">
    <div class="content">
    <p class="header"><%= "List:" %>
    <p class="header"><%= @list.list_name %>
    </p>

<%= "Tasks:" %>
<% @tasks.each do |task| %>
    <ul>
    <li><h1><%=task.task_name%></h1></li>
    <li><%= "Priority: " %><%= task.priority %>
    </ul>  
    <%= link_to "Show", list_task_path(@list, task), class: "ui blue button" %>
    <% end %>

    <hr />
    <br />
 
 <%= link_to "Add Task", new_list_task_path(@list) , class: "ui yellow button" %>

app/views/tasks/new.html.erb
 <h1>Add Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="ui card">
    <div class="content">
    <p class="header"><%= "Task:" %>
    <p class="header"><%= @task.task_name %>
    </p>
    
    <li><h3><%= "Priority: " %><%=@task.priority%></h3></li>
    <li><h4><%= "Description: " %><%=@task.description%></h4></li>
    </ul>
    
    <%= link_to "Edit", edit_list_task_path(@list, @task), class: "ui green button" %>
    <%= link_to "Delete", board_path(@list, @task), method: :delete, class: "ui red button" %>
    
 
 
 